global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: tempo
    static_configs:
      - targets: ['tempo:3100']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: express-rest-boilerplate
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']
